language: node_js
node_js:
- '8'
install:
- npm install -g codecov
script:
- yarn
- yarn run lint
- yarn codecov
- yarn build
- yarn types
deploy:
  skip_cleanup: true
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  tag: beta
  api_key:
    secure: Brx1Z4M2OdmnQ6hSxMCPHx5aroGGYfk36YEp9YhByi7Lj+ae9AsYWYG/CdspDEN8FxFQ+R2R/sjIDFtVLgxqWyujyjnpIo18K9l3InNN91Jn5ashBUZ2dhGEgxUxGWH/R5J2Fck+JiM2tN0XTfkvWo2wbLfRJuNTvIqo6IPcfEPtVjV1s6SFStoM4OBZ2TZaXTK6ZSVH92ojlit1LeGqlVJ1NcHzp3eQL6E7dGqj67Cq+7LQa/qWcvWR6rOpV7/x4sgVn44cT6W5msNO18vLNYLxyxAeiuv2ZA06UQs3IMbATtnSMzuSi2ppjjUNbrLbA/cyiUOQdt/xkTM3uUydvg9cpf2GQgywAA4oK2UEMXhB9IAVUv8R/9wpEALoktIId4k2yNfLpUSzlYSzuKAzvHzrQSASuM69YunGMsHyEey6xZoYdm5oy3M/6Iexo57aCWiJf2ACzvuFcfK0DhM4m83MELfwZW0zW/5WcgDEHit8mGZiIpYsoYmRvMryOK9fDhqyb3MnH+XoXYAl01dclwe7Mhqf6G9fgnUvsjTI4601pFCeyHi4GIvRgaRRLpwyu6a9nqGiXfmjfSfs7SYXDJ+eaYgTEwVwi7oAUqilznXOrUh21iPvVMV3YUREqFXu/JXRtW0ak+bF/M7yZoiRHMphnM8hkuPLoBK+K/U6S8U=
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro
notifications:
  slack:
    secure: ZrGsqnznXqlEHpB+1kSsxqKdtgNXZ5DMLTD3ThIH3H7XPyBCSshBtENJjZxlPpZBWsPBWTrZBGRHGgrsnaB06tFc44KeF4HqxPH0aH6P3oakYVOQD2HiaqSoDghClUngePREAKFKNAVi3AO50nu+TVYKUQoae1tdKY6ZV2OCJ86IbgXB775fn+kW+t0ODGUMtukpFfwTTZTDG5y1AxMojLrnEaoMgmIwwanPKpBiL0gXdRvEG5by31PHz4bA/0vUtR6W45OF7CUn6mO2Q96ZjQ1TKo6dYRymL8ySiOiVZaGbcVZzpjsaTHdq8ZdIqwzPnLPRax1MPQbxul6p1Xu8asHR51/eTZkaBNlAIB++n7YjLxiQuhjNnOFBjc/a1n3FK8h6KxOQikd0He8N+Q+Ksa1wBPNRVsN25VdpGkkAknMIC8YYTOgSkU6KUgeGwC1aVW9/Y/K+Bju2wZNAsF/JR0B7GiAEUWo3Bgx3OvAAuDC2LyWqsTVYMY8rFNZRhdXS/3NSlgxNhm6qphEk4FLFFb6aWbvkAKULwNFax7pe89BMuMEPcEac0ZS+InY3XOfC9ZT1VzqhW4SRih3qvqx9Dbe8tpJdFvmeOYXO78O6dQKGz/+/CVZUk5qKwv0965HmQMuBHYMFveSpbzcxE6ZqXKGUX239ua+GfQE+6FT7K/E=
env:
  global:
    secure: hdr+J22+7YjxcElpW56yj0qFi/nk1Y9SXycoqk7nQMSzEx7rT0exHWu8tqDA1e38AtdMVKwjkYxbm4w3c1W2QefdAyodWCCleTyZ2t7wl/b6qibVfxN4TEdQMPCDmv/buS1Y8eexKrn57eGNGu+OnZOGav0GjAl3jsIv7DoSjuaak5RR59+hq03ufh1KmCrlwUP0C0SAVGQ/SkhL/H1tbs5F9GdTM1U3Y+GepDPkyoIFNBmWSxqJVmJMDPqes9LfiffcTUaq1ko1y47xLPfQ7ZaXY/DzGcX/g+9XKsEfM9AsGmIKyzliw6ZIJ6lnjjajiTeq+3PPjicMSSevppUagFs9IveDAuPmn0g40Djyb9FrFZWhSs35PSFWWYhUgXHxRKh6T91wQZM3Np/Hx1WjXZoD3KxGnig4kfriUVrm3rvvikC4Fhn110xfoeu8fgE91PgGBMuMa9+V37qQfKElOFk1EUTuXCTJ6tMvOtBSNCqrOdiQaxKOAuDHOG+ej2k43SpOsmLi2asiWJ+DpfyrpekuvdLDuYUjq0XFfTbsKiCI0h8A0F2Tiwtc4mTFAcPlk49PHOsKsKFUKbGFTwSG3H53/e8+aZxH05XV1Y5uKxenNPGMlHVCRkKhdCK7nuClnbBAPSv3GgjFhiYvhteO15P0XiAahjC/Gs2pG8kSO3Y=
